'\" -*- coding: UTF-8 -*-
.TH psp2master 1 "September 2022" "psp2master"
.SH NAME
psp2master \- produce UMD\(rg master data from a PSP\(rg game image
.SH SYNOPSIS
.nf
\fBpsp2master\fR \fB\-i\fR \fIgame.iso\fR [\fB\-d\fR \fIoutdir\fR]
.fi
.SH DESCRIPTION
\fIpsp2master\fR will create UMD\(rg master data from a given PSP\(rg game iso.
Master data is suitable for use on a PSP\(rg TOOL system, such as the
DTP-H1500 or DTP-T1000.
.PP
The options to \fIpsp2master\fR are:
.TP
.B \-i
Specifies the PSP\(rg game image to be used.
.TP
.B \-d
Specifies the output directory for the UMD\(rg master data. If not
specified, the current directory will be used.
.SH AUTHOR
Jason Benaim <jkbenaim@gmail.com>
.SH COPYRIGHT
Copyright \(co 2022 Jason Benaim.
.br
Licensed under the GNU GPL version 3 or later.
.br
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.br
"PlayStation", "PSP" and "UMD" are registered trademarks of
Sony Computer Entertainment Inc.
