#pragma once
#define PSP2MASTER_PROGRAM_NAME "psp2master"
#define PSP2MASTER_URL "https://jrra.zone/psp2master"
#define PSP2MASTER_VERSION_STRING "1.1"
#define PSP2MASTER_VERSION_MAJOR (1)
#define PSP2MASTER_VERSION_MINOR (1)
#define PSP2MASTER_GENERATOR_STRING (PSP2MASTER_PROGRAM_NAME " " PSP2MASTER_VERSION_STRING)
#define PSP2MASTER_EMBLEM (PSP2MASTER_PROGRAM_NAME " " PSP2MASTER_VERSION_STRING "\nhttps://jrra.zone/psp2master\n")
