#pragma once
#define PSP2MASTER_PROGRAM_NAME "psp2master"
#define PSP2MASTER_URL "https://jrra.zone/psp2master"
#define PSP2MASTER_VERSION_STRING "1.0"
#define PSP2MASTER_GENERATOR_STRING (PSP2MASTER_PROGRAM_NAME " " PSP2MASTER_VERSION_STRING)
